
version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/Project2Backend-0.0.1-SNAPSHOT.jar Project2Backend-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - Project2Backend-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: AWS-CodePipeline-Project2-Service
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/java:openjdk-8
  Timeout: 60
  base-directory: 'target/Project2Backend'
